// <auto-generated />
using System;
using System.Collections.Generic;
using EnergyApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnergyApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnergyApp.API.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EnergyApp.API.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("EnergyApp.API.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EnergyApp.API.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EnergyApp.API.Models.ElectricityBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BillingCycle")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocReceiveNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FtRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PeaAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PeaUnitUsed")
                        .HasColumnType("numeric");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ElectricityBills");
                });

            modelBuilder.Entity("EnergyApp.API.Models.ElectricityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BillingCycle")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocReceiveNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FromBatteryWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FromGridWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FromSolarWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FtRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PeaAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PeaUnitUsed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProductionWh")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SolarUnitProduced")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToBatteryWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToGridWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToHomeWh")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ElectricityRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.FuelReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeclarerDept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeclarerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeclarerPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntriesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("FuelReceipts");
                });

            modelBuilder.Entity("EnergyApp.API.Models.FuelRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GasStationCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Liters")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefuelDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleProvince")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FuelRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.FuelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("EnergyApp.API.Models.IPPhoneCallLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AnsweredInbound")
                        .HasColumnType("integer");

                    b.Property<int>("AnsweredOutbound")
                        .HasColumnType("integer");

                    b.Property<int>("BusyInbound")
                        .HasColumnType("integer");

                    b.Property<int>("BusyOutbound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedInbound")
                        .HasColumnType("integer");

                    b.Property<int>("FailedOutbound")
                        .HasColumnType("integer");

                    b.Property<int>("NoAnswerInbound")
                        .HasColumnType("integer");

                    b.Property<int>("NoAnswerOutbound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportMonth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCalls")
                        .HasColumnType("integer");

                    b.Property<int>("TotalInbound")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOutbound")
                        .HasColumnType("integer");

                    b.Property<string>("TotalTalkDuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VoicemailInbound")
                        .HasColumnType("integer");

                    b.Property<int>("VoicemailOutbound")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IPPhoneCallLogs");
                });

            modelBuilder.Entity("EnergyApp.API.Models.IPPhoneDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalogNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Workgroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IPPhoneDirectories");
                });

            modelBuilder.Entity("EnergyApp.API.Models.IPPhoneMonthStat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportMonth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IPPhoneMonthStats");
                });

            modelBuilder.Entity("EnergyApp.API.Models.MeetingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RecordMonth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecordedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MeetingRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.MeetingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MeetingRooms");
                });

            modelBuilder.Entity("EnergyApp.API.Models.PostalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("EmsMail")
                        .HasColumnType("integer");

                    b.Property<int>("IncomingEmsMail")
                        .HasColumnType("integer");

                    b.Property<int>("IncomingNormalMail")
                        .HasColumnType("integer");

                    b.Property<int>("IncomingRegisteredMail")
                        .HasColumnType("integer");

                    b.Property<int>("IncomingTotalMail")
                        .HasColumnType("integer");

                    b.Property<decimal>("EmsMailUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("NormalMail")
                        .HasColumnType("integer");

                    b.Property<decimal>("NormalMailUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordMonth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegisteredMail")
                        .HasColumnType("integer");

                    b.Property<decimal>("RegisteredMailUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalMail")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PostalRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SarabanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FromOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToOrganization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SarabanRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminOfficerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminOfficerUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClosedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClosedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExternalCompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExternalResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExternalScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExternalVendorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCentralAsset")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterDepartmentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterDepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("SupervisorCanRepairInHouse")
                        .HasColumnType("boolean");

                    b.Property<string>("SupervisorExternalAdvice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorRepairPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupervisorUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianDiagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WorkOrderNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SolarProduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FromBatteryWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FromGridWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FromSolarWh")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductionWh")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SolarUnitProduced")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToBatteryWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToGridWh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToHomeWh")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SolarProductions");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePartIssueRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApprovedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SparePartIssueRequests");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePartIssueRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyApproved")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QtyRequested")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SparePartIssueRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SparePartId");

                    b.HasIndex("SparePartIssueRequestId");

                    b.ToTable("SparePartIssueRequestItems");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePartTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedByUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SparePartId")
                        .HasColumnType("uuid");

                    b.Property<string>("TxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SparePartId");

                    b.ToTable("SparePartTransactions");
                });

            modelBuilder.Entity("EnergyApp.API.Models.TelephoneRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BillingCycle")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocReceiveNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsageAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TelephoneRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("AccessibleSystems")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("AdminSystems")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnergyApp.API.Models.WaterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BillingCycle")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CurrentMeter")
                        .HasColumnType("numeric");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocReceiveNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonthlyServiceFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RawWaterCharge")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReadingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UsageAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WaterAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WaterUnitUsed")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("WaterRecords");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePartIssueRequestItem", b =>
                {
                    b.HasOne("EnergyApp.API.Models.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnergyApp.API.Models.SparePartIssueRequest", "SparePartIssueRequest")
                        .WithMany("Items")
                        .HasForeignKey("SparePartIssueRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SparePart");

                    b.Navigation("SparePartIssueRequest");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePartTransaction", b =>
                {
                    b.HasOne("EnergyApp.API.Models.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("EnergyApp.API.Models.User", b =>
                {
                    b.HasOne("EnergyApp.API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EnergyApp.API.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EnergyApp.API.Models.SparePartIssueRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
